### ISSUE TITLE
Permanent(nil) should return nil

### ISSUE THREAD

**Issue by bobg** [cenkalti/backoff#100]
For convenience, it should be safe to return `Permanent(err)` from a function without first having to check whether `err` is `nil`. This would be analogous to how `errors.Wrap` works (see https://godoc.org/github.com/pkg/errors#Wrap).

**Comment by bobg** [comment]
Implementation here: https://github.com/cenkalti/backoff/compare/v4...bobg:v4

Had to change the signature of `Permanent` to return an `error` rather than a `*PermanentError`, because `(*PermanentError)(nil)` does not compare equal to `error(nil)`.

**Comment by cenkalti** [comment]
Hello @bobg. Good catch. I have merged your commit into `development` branch. Since this is a backwards-incompatible change, it has to wait for v5.

**Comment by bobg** [comment]
Cool, thanks!

**Comment by ptrus** [comment]
This is included in the 4.1 release, so can probably close the issue.
