### ISSUE TITLE
feat: Add method to get current internval for BackOff

### ISSUE THREAD

**Issue by j2gg0s** [cenkalti/backoff#104]
Thanks this wonderful project.

When i use BackOff, I want to get current internval.
Do we need pr for this feature?

**Comment by cenkalti** [comment]
With current API, when `NextBackOff` is called, internal state is changed and a duration is returned. Do you need a method for returning the duration without changing internal state? What's your use case?

**Comment by j2gg0s** [comment]
Within function ``Retry(o Operation, b BackOff)``, I want to log event with current backoff when retry happend.

``NextBackOff`` is not a get method, call this function change backoff's state.

**Comment by cenkalti** [comment]
You can use `RetryNotify` function for that.

https://pkg.go.dev/github.com/cenkalti/backoff?tab=doc#RetryNotify
