### ISSUE TITLE
Usage in multiple go routines

### ISSUE THREAD

**Issue by antiphp** [cenkalti/backoff#105]
Hey,

I want to use one backoff strategy multiple times concurrently. Basically request a URL in a loop and each request runs in a Go routine. Is my assumption correct that using the same backoff instance is not concurrency-safe? My suggestion would be to provide a clone/copy functionality which would be called within the loop. If necessary and welcomed, I can create a PR for that - ofc only if my assumption is correct.

(This is more a question / feature request than an issue. Sorry if this is not the right place)

Cheers

**Comment by cenkalti** [comment]
Yes, the same backoff instance is not concurrency-safe. Can't you just copy the variable?
```
b := NewExponentialBackOff()
b2 := *b
```

**Comment by antiphp** [comment]
Nah that would be too easy. OMG ok thanks.
