### ISSUE TITLE
Builder pattern using functional options

### ISSUE THREAD

**Issue by jhollowayj** [cenkalti/backoff#106]
Right now, it's a little weird to create a backoff that has max tries, and context, and set the delay amount (zero, constant, exponential, never).

What are your thoughts on changing the interface to be something more like this:

```go
backoff.NewBackoff(
    backoff.WithConstantDelay(500 * time.Millisecond),
    backoff.WithContext(ctx), 
    backoff.WithMaxTries(4), 
)
```

I'm not sure if I would want to put the delay amount as an argument, or maintain the existing constructors for each type.
`backoff.WithConstantDelay(...)`, `backoff.WithExponentialDelay(...)`, `backoff.WithZeroDelay()`, `backoff.WithNoRepeat()`.
vs
`backoff.NewConstantBackoff(...)`, `backoff.NewExponentialBackOff(...)`, ...

I think this would require rewritting the backoff logic to combine support for context and max tries into the base backoff objects.

Thoughts?

Related reading: https://github.com/tmrts/go-patterns/blob/master/idiom/functional-options.md

**Comment by cenkalti** [comment]
Hi @jhollowayj. I don't plan rewriting of this library but Option pattern can be implemented for v5 in future.

**Comment by thediveo** [comment]
@cenkalti could you live with not breaking the API (not even on source level) but with adding the `New...WithOpts` siblings accepting options instead, similar to what was done with Docker's go-client API?

**Comment by cenkalti** [comment]
Hi @TheDiveO. The library is in stable state and I don't want to make any changes. v5 probably never going to happen. Sorry.

**Comment by thediveo** [comment]
why?
