### ISSUE TITLE
Use errors.As instead of type assertions for Permanent error

### ISSUE THREAD

**Issue by ptrus** [cenkalti/backoff#107]
In https://github.com/cenkalti/backoff/issues/79 `Unwrap()` implementation was added to the `Permanent` error type.
The check for `Permanent` error can now be changed to use [errors.As](https://golang.org/pkg/errors/#As), instead of using type assertion as it is done currently:
https://github.com/cenkalti/backoff/blob/31cc31bb63269a3c813d1f26e0ab058452b7d803/retry.go#L56-L58

Benefit of using `errors.As` is that it will also match wrapped permanent errors, for which the currently used type assertion fails.

Additional note: `Permanent` is missing an implementation for [Is(error) bool](https://golang.org/pkg/errors/#Is). If the `Is` implementation is added, [errors.Is](https://golang.org/pkg/errors/#Is) can be used instead.

**Comment by cenkalti** [comment]
@ptrus good point. Can you send PR?

**Comment by ptrus** [comment]
Sure, will do

**Comment by cenkalti** [comment]
@ptrus Thanks 🍰
