### ISSUE TITLE
v4.1.2 tag points to same commit as v4.1.1

### ISSUE THREAD

**Issue by loafoe** [cenkalti/backoff#119]
Noticed this when @dependabot created a PR for an upgrade, but no change between the two versions. 
Is this intended?

Thanks BTW for this great library!

**Comment by cenkalti** [comment]
No, it was not intended. Thanks for reporting it. Does this cause any problem?

**Comment by loafoe** [comment]
@cenkalti no issue other than dependabot PRs which are NOOPs apart from the version change :)
