### ISSUE TITLE
Generic retry function?

### ISSUE THREAD

**Issue by veqryn** [cenkalti/backoff#125]
Right now the Retry function takes an `Operation` type, which is `type Operation func() error`, such that that you can call it like so:
```golang
func somethingThatMightFail() (int, error) {
    return 123, nil
}

err := backoff.Retry(
    func() error {
        _, err := somethingThatMightFail()
        return err
    },
    boff,
)
```

With generics, it would be nice to have a new Retry function that could also return a variable.  Such as:
```golang
func RetryGeneric[T any](o func() (T, error), b Backoff) {
    // Do the retry stuff, return T and err
}
```

Then use it like so:
```golang
t, err := backoff.RetryGeneric[int](
    somethingThatMightFail,
    boff,
)
```

I think most functions out there return something plus an error, so this plus the existing API would cover the vast majority of functions that you may want to retry.

An example of the current helper function I use:
```golang
func RetryNotify[T any](operation func() (T, error), boff backoff.BackOff, notify func(error, time.Duration)) (T, error) {
	var t T
	var err error
	err = backoff.RetryNotify(
		func() error {
			t, err = operation()
			return err
		},
		boff,
		notify,
	)
	return t, err
}
```

**Comment by ItalyPaleAle** [comment]
We (Dapr) need this too so I opened #126.

Sadly, the workaround you're using (and which we've been using within Dapr) can lead to race conditions in certain cases

**Comment by veqryn** [comment]
@ItalyPaleAle question: in the helper example, where is the race condition?

**Comment by ItalyPaleAle** [comment]
> in the helper example, where is the race condition?

Uh, actually, nevermind, that was specific to the way we used this library in Dapr 🙃 (We have a wrapper that uses a goroutine)

**Comment by veqryn** [comment]
@ItalyPaleAle ah ok. Hopefully your PR gets accepted, it is much cleaner for all users.
