### ISSUE TITLE
[security] Set minimum workflow permissions

### ISSUE THREAD

**Issue by gabibguti** [cenkalti/backoff#130]
Set minimum permissions for workflows is important to keep your repo safe against supply-chain attacks. I'd like to suggest that we set `contents: read` permission for the `go.yml` workflow, even if it's only used for tests. This helps make sure the GITHUB_TOKEN inside the workflow context does not have unnecessary access. By default, GitHub grants higher permissions for GITHUB_TOKEN. For example, it grants access to `contents: write`, which allows to create new commits and make other modifications to your repository. It would be good if we can restrict this access.

If you agree with the changes, I can open a PR.

##### Additional context
I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by cenkalti** [comment]
Thanks. Can you open a PR?
