### ISSUE TITLE
[security] Add security policy

### ISSUE THREAD

**Issue by gabibguti** [cenkalti/backoff#132]
Adding a Security Policy is important to inform how users can report security vulnerabilities. If you agree with adding a Security Policy, I can open a PR to suggest one, and we can work together to communicate how the repo can best handle these vulnerability reports.

##### Additional Context
Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by csh0101** [comment]
I'm a student now. so just for my interests, i write this comment. what means Security Policy? Just a  Security.MD?  So maybe this is helpful for dependency track?

**Comment by gabibguti** [comment]
@csh0101 Yes! By Security Policy I mean a SECURITY.md file. The purpose of this file is to guide users, that found vulnerabilities in your code, to report them. A vulnerability here could be defined as a "breach" in your code that could be used to perform malicious actions, such as stealing credentials. For that purpose, we wanna instruct differently how to make these reports and separate them from normal issues. That said, I don't see how this could be used for dependency track, I believe there are other tools to track dependencies.

**Comment by csh0101** [comment]
make sense! @gabibguti . thanks very much! But I Means the dependency track is the `Dependency Track`,the project of  OWSAP. I imagine the SECURITY.md maybe will be  recorded by some vulnerability intelligence sources. in this context, maybe point to Github? ....But maybe you're right, if the Security.MD is a not standard format documents, it is not best proper material to collect vulnerabilities.. 
I'm sorry, it's unclearly when I say the word `dependency track`,maybe it bother you. 
Finally，very thanks to your answer.

**Comment by gabibguti** [comment]
Hi! Friendly ping here. This issue has been idle for quite some time. Do you plan on considering these changes? If yes, please let me know! Otherwise I will wait up to 2 more months to close the issue. Thanks!

**Comment by cenkalti** [comment]
I don't think this project needs a security policy. Thank you!
