### ISSUE TITLE
Allow Operation function to return minimum interval to wait in backoff

### ISSUE THREAD

**Issue by ItalyPaleAle** [cenkalti/backoff#134]
Example: the function invoked by backoff makes HTTP requests, and the server responds with a 429 ("retry after") status code.

We want the Operation function to be able to return an error which indicates that the next backoff should not happen before the given delay.

For example, assume that the next backoff is in 1s, but the server responds with a "Retry-After" indicating a 5s delay. The handler should return a special kind of error (for example, `MinBackoffError`, similar to `PermanentError`) that indicates that the next attempt should not happen in less than 5s.

The backoff library will then pick the maximum of the 2 (1s and 5s) and use that as the next backoff.

I am happy to submit a PR if you think you would be interested in this!

**Comment by cenkalti** [comment]
In v5, now you can return `backoff.RetryAfterError` to signal how long to wait.

https://github.com/cenkalti/backoff/blob/3bc9b4c7c864eb141de969f7daa98387184f21a8/example_test.go#L32-L39
