### ISSUE TITLE
[enhancement] Add Functional Options for Configuring ExponentialBackOff

### ISSUE THREAD

**Issue by KhanSufiyanMirza** [cenkalti/backoff#136]
**Description:**
As part of enhancing the usability of the `backoff` library, I propose adding functional options for configuring the `ExponentialBackOff` struct. Functional options provide a more flexible and extensible way to set various parameters for the `ExponentialBackOff`.

**Feature Details:**
- Add functional options for `InitialInterval`, `RandomizationFactor`, `Multiplier`, `MaxInterval`, `MaxElapsedTime`, `StopDuration`, and `Clock`.
- Update `NewExponentialBackOff` to accept these functional options.

**Expected Behavior:**
Developers will be able to easily configure the `ExponentialBackOff` struct with the desired parameters using functional options. This will make the library more user-friendly and customizable.
`backOff := NewExponentialBackOff(
		WithInitialInterval(1*time.Second),
		WithMultiplier(2.0),
		WithMaxInterval(10*time.Second),
		WithMaxElapsedTime(30*time.Second),
		WithRetryStopDuration(0),
		WithClockProvider(SystemClock),
	)`

**Motivation:**
This feature will enhance the library by allowing users to configure the `ExponentialBackOff` struct in a more intuitive and extensible way. It aligns with best practices for creating flexible APIs.

**Additional Information:**
- I have prepared the code changes and unit tests.
- A pull request is submitted.

Please let me know your thoughts and whether this feature aligns with the project's goals.

**Comment by jcass8695** [comment]
@cenkalti could you create a tag for this please?

**Comment by rcontreras-te** [comment]
@cenkalti  `v4.2.1` doesn't have this in it... could we get a next release please? (cc: @KhanSufiyanMirza )

**Comment by cenkalti** [comment]
Tagged as v4.3.0
