### ISSUE TITLE
Require tests before merging

### ISSUE THREAD

**Issue by gabibguti** [cenkalti/backoff#138]
It may be a good addition to request tests to pass before merging. Having passing tests on pull requests can help assure for the maintainers and contributors that the changes are working before being merged into the source code.

backoff already has a `test.yml` workflow and it's configured to run on pull requests, but workflows need to be approved to run for first-time contributors. To help ensure we don't forget running the tests, we can setup a Branch Protection with "Require status checks" and add `build` (the job that runs the tests in `test.yml`) to be required for merging.

If the approval step is what's blocking us from running tests before merging, then we can additionally [change the "Fork pull request workflows from outside collaborators" Action setting to "Require approval for first-time contributors who are new to GitHub"](https://github.com/cenkalti/backoff/settings/actions). Since the workflow now has minimum permissions, don't use any other critical credentials and does not have dangerous patterns, the outside contributors are not able to attack through this workflow.

##### Additional context

Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by gabibguti** [comment]
Hey! Friendly ping here. Do you think it would be useful to request tests to pass before merging? If there's no response, I will understand this may not be planned for now and I will close the issue in 2 months to avoid flooding the issues tab.

**Comment by cenkalti** [comment]
Hi @gabibguti . I have made the changes you mentioned. Thanks!
