### ISSUE TITLE
MaxInterval is not the actual maximum interval

### ISSUE THREAD

**Issue by jayjanssen** [cenkalti/backoff#139]
Despite having MaxInterval set to 1 Minute, I regularly get intervals over 1 minute.  This appears to be due to https://github.com/cenkalti/backoff/blob/v4.2.1/exponential.go#L155

Shouldn't that line simply read:
```
var maxInterval = float64(currentInterval)
```

**Comment by jayjanssen** [comment]
I see this is a duplicate of https://github.com/cenkalti/backoff/issues/117

I still disagree with it, but it's your module I suppose.

**Comment by stevenh** [comment]
Ahh yes that's confusing, caught me out, I want the randomisation but before the cap.

**Comment by stevenh** [comment]
I worked around this using following where my target max was 250ms
```go
MaxInterval:    time.Duration(float64(time.Millisecond*250) * backoff.DefaultRandomizationFactor),
```
