### ISSUE TITLE
Exponential backoff doesn't seems to work

### ISSUE THREAD

**Issue by fatih** [cenkalti/backoff#14]
```go
package main

import (
	"fmt"

	"github.com/cenkalti/backoff"
)

func main() {
	b := backoff.NewExponentialBackOff()

	fmt.Println(b.NextBackOff())
	fmt.Println(b.NextBackOff())
	fmt.Println(b.NextBackOff())
	fmt.Println(b.NextBackOff())
	fmt.Println(b.NextBackOff())
}
```

Output:

```bash
-1ns
-1ns
-1ns
-1ns
-1ns
```

```sh
~/demo  go version
go version go1.4.2 darwin/amd64
```

**Comment by nightlyone** [comment]
@fatih add a `b.Reset()` before you call `b.NextBackOff()` the first time. Than it works.

@cenkalti should this be done automatically on initialization or will this break the usage/algorithms?

**Comment by fatih** [comment]
I've found the solution for it. But I would except that Reset would be called by default. Though it breaks the test.

**Comment by cenkalti** [comment]
I did a direct translation from the java client, unfortunately forgot to add reset call in the constructor: https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/util/ExponentialBackOff.java#L171

I would like to add it now and I think it does not break backwards compatibility.

**Comment by nightlyone** [comment]
awesome! Thanks for fixing this @cenkalti :+1:
