### ISSUE TITLE
Does not retry wrapped PermanentError  

### ISSUE THREAD

**Issue by RoryCrispin** [cenkalti/backoff#140]
When the retry Op returns a wrapped PermanentError - the library does not recognise it as a Permanent Error (as the type cast to *PermanentError fails.

This is unexpected in my opinion. It would be more idiomatic to respect the usual Go error wrapping rules and test with `errors.Is`. 
I'll be happy to raise a PR for this change

**Comment by cenkalti** [comment]
Yes. Can you send a PR?

**Comment by roman-baldaev** [comment]
Is this still relevant? I faced the same issue.

**Comment by kvij** [comment]
I wonder what causes this. As far as I can see the code uses `errors.As` which does the same traversal as `errors.Is`.
Are you using v4 and if so can you show some example code?

**Comment by cenkalti** [comment]
Related #144

**Comment by cenkalti** [comment]
I believe this is fixed in v5.

**Comment by andig** [comment]
@RoryCrispin could you share a test case? I'd like to fix this for v4.
