### ISSUE TITLE
Clone support

### ISSUE THREAD

**Issue by nemith** [cenkalti/backoff#141]
It is nice to put any backoff into a configuration struct, but ideally once it has been configured I want to "lock in" the settings after done.  To do this it may just be nice to clone the BackOff object.

If you ever think about a v5 it could be nice to have a Clone() (or an extension interface) method to clone the backoff with new values so that the passed in version is locked inside my implemenation/api.

e.g.
```
type Fooer struct {
   bo backoff.BackOff
}

func NewFooer(retryBackoff backoff.BackOff) *Fooer {
   return &Fooer{
      bo: retryBackoff.Clone(),
   }
}
```

Since `bo` is not exported now the user of my API cannot modify the backoff pointer outside of my implementation but can still provide any backoff implementation they desire. 

Super low priority, just dropping here as an idea.

**Comment by nemith** [comment]
No discussion?

**Comment by cenkalti** [comment]
Sorry for closing without discussion.

You could create a separate function to initialize a new backoff object with the desired configuration. This approach avoids modifying the existing object and ensures immutability.
