### ISSUE TITLE
RetryNotify does not deal with operations that hang, even if a timeout is set

### ISSUE THREAD

**Issue by MattCosturos** [cenkalti/backoff#146]
I have 0 experience developing in go, so please be gentle if I misunderstand any of the inner workings of multi-threaded go development.
However to me, it appears that RetryNotify does not deal with operations that hang, even if a timeout is set.

RetryNotify uses RetryNotifyWithTimer uses doRetryNotify

doRetryNotify 
Line 87 starts a for loop.
Line 88 calls the provided operation() 
This is a blocking call. It waits for operation to return, and checks the return value.
Further down is a select block to wait for ctx.Done(), or the result of a timer.
But if operation() on line 88 blocks we would never get here?

I would imagine you need some code like the following inside the for loop. Again, I have 0 experience in go, this is based off what I've learned in the past 24 hours.

```
	errCh := make(chan error)
	resCh := make(chan res)

	go func() {
		res, err := operation()
		if err != nil {
			errCh <- err
			return
		}
		resCh <- res
	}()

	select {
	case <-ctx.Done():
		return ctx.Err()
	case err := <- errCh
		//do the error logic here
	case res := <- resCh
		return res, nil
	}
```

**Comment by MattCosturos** [comment]
Submitted  PR #147 which keeps functionality the same (all existing test cases pass) and adds a test for a blocked operation

**Comment by cenkalti** [comment]
If an operation is hanging or blocked, you should handle it in your code. It's not right to continue execution and let the operation keep running. This would cause leaking goroutines.

**Comment by elena-kolevska** [comment]
> If an operation is hanging or blocked, you should handle it in your code. It's not right to continue execution and let the operation keep running. This would cause leaking goroutines.

Thanks for the reply @cenkalti ! I understand your point of view, but as a user, when I see I can create a backoff as `NewBackOff()` or `NewBackOffWithContext` I would expect that the context I'm passing into the latter will be respected, otherwise it would be the same as the regular backoff. Am I understanding this correctly?

**Comment by MattCosturos** [comment]
> If an operation is hanging or blocked, you should handle it in your code. It's not right to continue execution and let the operation keep running. This would cause leaking goroutines.

Makes sense that we would want to avoid leaking goroutines.

Question - since this library is the one actually invoking the goroutine, could we then kill the hung task (in the case of a hang) and return the context exceeded error to the caller?

Also, ignoring routines that hang, the current library does not respect the timeout for routines that don't hang or succeed after the context has expired.

Example 1 - Call succeeds on first try, but takes 30 seconds. Called with a timeout of 15 seconds.
The actual behavior is the calling code waits for 30 seconds, and gets the successful result.

Example 2 - Call fails on first try, but takes 30 seconds. Called with a timeout of 15 seconds.
The actual behavior is the calling code waits for 30 seconds, then gets the context expired result. After the first call fails, the retry logic kicks in, sees the timeout has expired, and returns a timeout

Example 3 - Call fails on first try, succeeds on second try ,and takes 2 seconds each time.
The actual behavior is the calling code waits for 4 seconds total, and gets the successful result. The retry logic works as designed, retrying the call as long as the context is not expired.

Example 4 - Call fails every time, takes 2 seconds each time.
The actual behavior is the calling code waits for 16 seconds total, and gets the context expired result. The retry logic works as designed, retrying the call as long as as the context is not expired.

Example 1  is the case that is most non-intuitive to me, based on the description of the function and the arguments provided.
If I provide a timeout of 15 seconds, I expect a call to succeed is 15 seconds or less, or fail. I don't expect it to succeed after 15 seconds. 
The initial case that we found was a hang, but any call that takes longer than the timeout leads to this mildly confusing behavior.

**Comment by cenkalti** [comment]
> since this library is the one actually invoking the goroutine

This is not correct. The library executes the operation function as a regular function call:
https://github.com/cenkalti/backoff/blob/31e2809de639dbeb03264b6bc37c9e7d3f522a7b/retry.go#L87

Since the operation is implemented in the application code, cancellation must be handled there too.
