### ISSUE TITLE
Remove Retry* methods

### ISSUE THREAD

**Issue by cenkalti** [cenkalti/backoff#148]
<img width="235" alt="image" src="https://github.com/user-attachments/assets/7759cff3-7c5c-4ff2-8ece-5b1c87cff185" />

Remove these methods from the library because they are complex. 

Give users clear examples and guidelines to help them create their own logic.

**Comment by cenkalti** [comment]
Done in v5.

**Comment by andig** [comment]
I have quite a bit of code that just needs to succeed:

```go
		if err := backoff.Retry(func() error {
			return wb.post(salia.HeartBeat, "alive")
		}, bo); err != nil {
			wb.log.ERROR.Println("heartbeat:", err)
		}
```

or

```go
if err := backoff.Retry(func() error {
	return backoffPermanentError(client.GetJSON(uri, &res))
}, bo()); err != nil {
       ...
}
```

where the result is not directly returned (but of course could be in this case) but simply written to. This is now becoming a little more awkward with having to 

a) ignore the final data, but worse
b) return an uneeded type from the operation

It's really unfortunate this is no longer possible? Maybe add an `RetryError` that handles this internally using an unexported type?

**Comment by andig** [comment]
A less breaking variant of v5 might have been keeping `Retry` and adding a (simpler) `RetryResult` instead of `RetryWithData` or just keeping `RetryWithData`.

**Comment by hurrycaine** [comment]
Dito @andig comments - I am perplexed after 4 versions we are now only allowing retry if it returns (T, err) instead of just error. If its to late to change could we add a func that just does the  original func() error.

**Comment by andig** [comment]
I'd like to make a bold suggestion: release `v6` with `Retry` as it was and `RetryWithData` as before. This will allow upgrading for everyone without breaking changes. `Retry` becomes a library-provided wrapper for `RetryWithData` that never needs to be touched again and should not impact maintenance. I've decided to stay on v4 for time being since v5 as it is forces me to change every instance of invocation without adding value (no pun intended!).

**Comment by cenkalti** [comment]
Thanks for the suggestion @andig. I'll stick with the current implementation of Retry in v5 for now. Breaking changes are expected between major versions, which helps create a cleaner API in the future. If v4 meets your needs better, that's a valid choice.

**Comment by andig** [comment]
Indeed, I've stuck to v4 since the v5 api just makes my code uglier than before and uglier than it really needs to be.

**Comment by andig** [comment]
https://github.com/cenkalti/backoff/issues/152#issuecomment-5425411070
