### ISSUE TITLE
Allow for conditional errors

### ISSUE THREAD

**Issue by doodles526** [cenkalti/backoff#19]
Add a set of functions such as
```
func ConditionalRetry(o Operation, c Conditional, b Backoff) error
func ConditionalRetryNotify(o Operation, c Conditional, n Notify, b Backoff) error
```
where
```
func Conditional(e error) bool
```
The idea being that some operations return errors, and you only want to backoff on certain errors. Otherwise you just want to drop the error through to the receiver of `ConditionalRetry` or `ConditionalRetryNotify`

I already implemented a hacky version of this for a project that I needed to have that functionality. If there's interest of supporting this I could clean up what I have and throw up a PR

**Comment by cenkalti** [comment]
Why not simply wrap the operation function?

Example:
```go
operation := func() error {
    err := realOperation()
    if err == ErrNotThatBad {
        return nil
    }
    return err
}
```
