### ISSUE TITLE
Better retry example

### ISSUE THREAD

**Issue by fatih** [cenkalti/backoff#20]
The example below is simple and shows with logs what's happening. I think it's better if we replace the example in the docs with this. I'll open PR when I have time, for now I just paste it here:

```go
package main

import (
	"fmt"
	"log"

	"github.com/cenkalti/backoff"
)

func main() {
	if err := realMain(); err != nil {
		log.Fatalln(err)
	}
}

func realMain() error {
	count := 0

	operation := func() error {
		if count != 10 {
			count++
			log.Printf("Count is '%d'. Needs to be '10'", count)
			return fmt.Errorf("Not finished")
		}

		log.Println("Operation succedded")
		return nil
	}

	log.Println("Calling backoff.Retry")
	err := backoff.Retry(operation, backoff.NewExponentialBackOff())
	if err != nil {
		// Handle error.
		return err
	}

	log.Println("Operation is finished")
	return nil
}
```

**Comment by frodopwns** [comment]
This is an improvement.  The other examples are terrible.

**Comment by cenkalti** [comment]
I am quite busy. If someone can send a PR I'll merge.

**Comment by cenkalti** [comment]
I have removed the package example since it's too complex. The example provided by @fatih is similar to https://godoc.org/github.com/cenkalti/backoff#example-Retry

I am closing this for now.

**Comment by xild** [comment]
I think this is still necessary... 

@cenk do you think is a bad idea put some examples in README.md? 

This makes the package more friendly for everyone.

I can provide some examples in a new PR.

**Comment by cenk** [comment]
Hello @xild. There is already a link to some examples in README file. I don't think it is hard to understand how to use the package. Besides, putting examples into README creates duplication. Godoc page serves its purpose well.

**Comment by xild** [comment]
@cenk Hi cenk...

Thinking over many golang's package, as mentioned above, it is possible to suggest that with more accessible information for any kind of users (advanced or non-advanced), the package could have more users, and a high amount of users would bring improvement and developments.

For me isn't the kind of thing that it is hard, but something that can be easier.
