### ISSUE TITLE
ExponentialBackoff thread safety

### ISSUE THREAD

**Issue by talbright** [cenkalti/backoff#21]
What makes this type not thread-safe? 

https://github.com/cenkalti/backoff/blob/master/exponential.go#L52

Only thing I can see is a possible issue here https://github.com/cenkalti/backoff/blob/master/exponential.go#L103.

**Comment by cenkalti** [comment]
There is a race condition when ```NextBackOff()``` is called from multiple threads. ```currentInterval``` field is not protected from reading/writing from different threads.

**Comment by talbright** [comment]
Yup makes sense. Thanks!
