### ISSUE TITLE
Retriability is orthogonal to error

### ISSUE THREAD

**Issue by atombender** [cenkalti/backoff#22]
This library is nice, but makes it awkward to classify errors as retriable or not.

The retriable function can either fail in a way that is retriable, or it can fail permanently. Permanent failure needs to be propagated, but since `Retry()` uses the error return to detect whether something should be retired, you need an additional error variable to track this. For example:

```go
var fail error
err := backoff.Retry(func() error {
  resp := doSomeKindOfHttpRequest()
  if resp.Status == 404 {
    fail = errors.New("Not found")
    return nil  // Don't retry, though it failed
  }
  if resp.Status == 503 {
    return errors.New("Unavailable")  // Retry
  }
  return nil
}, backoff.NewExponentialBackOff())
if err != nil {
  return err
}
if fail != nil {
  return fail
}
```

The solution is to let `Operation`'s signature be:

```go
type Operation func() (err error, retriable bool)
```

...and only retry if it returns true. If it returns false, its error should be returned from `Retry()`. Rewritten example:

```go
err := backoff.Retry(func() (error, bool) {
  resp := doSomeKindOfHttpRequest()
  if resp.Status == 404 {
    return errors.New("Not found"), false
  }
  if resp.Status == 503 {
    return errors.New("Unavailable"), true
  }
  return nil, false
}, backoff.NewExponentialBackOff())
if err != nil {
  return err
}
```

Another way would be to a have a pluggable "policy function" that can look at an error and determine if it's retriable, but that's probably too Javaesque for a simple library like this.

**Comment by cenkalti** [comment]
As your proposal suggests changing of function signature it will not happen to not break applications using this package.

If you don't like it this way you can copy ```Retry``` function into your program and modify it as you like. It is a very small function.

**Comment by atombender** [comment]
So you can never change the public interface? That's disappointing.

**Comment by cenkalti** [comment]
Sorry, no.
