### ISSUE TITLE
Better fork at github.com/azr/backoff?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [cenkalti/backoff#31]
I often stumble upon projects are using the https://github.com/azr/backoff/ fork. I wish those commits are brought here.

**Comment by cenkalti** [comment]
https://godoc.org/github.com/cenkalti/backoff
https://godoc.org/github.com/azr/backoff

The fork introduces backwards incompatible changes which I cannot bring into this package. This package is being used in many projects and it is too late for API changes.
