### ISSUE TITLE
May I update Travis go version ?

### ISSUE THREAD

**Issue by dvrkps** [cenkalti/backoff#48]
@cenkalti I want to update Go version in Travis file from 1.3.3 to 1.x(latest stable) or more explicit 1.9.x ?

**Comment by cenkalti** [comment]
Yes, that would be great but please add it as new item without replacing the old version.

**Comment by dvrkps** [comment]
Why is 1.3.3 important ?

**Comment by cenkalti** [comment]
I just don't want break other people's builds.

**Comment by dvrkps** [comment]
Done.
