### ISSUE TITLE
SetFinalizer appears ineffective

### ISSUE THREAD

**Issue by Groxx** [cenkalti/backoff#56]
I was browsing through the code, and noticed the `runtime.SetFinalizer(ticker, stop)` call at https://github.com/cenkalti/backoff/blob/master/ticker.go#L37

I suspect it doesn't work.  As far as I understand it, goroutines are "gc roots" like in practically every other language, so as long as the `run` goroutine is running there is always something referencing the ticker, so it never gets garbage collected.

A quick test fails tor produce any "finalizer ran" results:
```
import (
	"testing"
	"time"
	"runtime"
)

type ticker struct{}
func (t *ticker) run() {
	// run forever and just keep sleeping
	for {
		<- time.After(10 * time.Millisecond)
	}
}

func runner(t *testing.T) {
	thing := ticker{}
	go thing.run()
	runtime.SetFinalizer(&thing, func(_ *ticker){ t.Log("Finalizer ran")})
}

func TestGc(t *testing.T) {
	runner(t)
	t.Log("Before sleep")
	<-time.After(100 * time.Millisecond)
	t.Log("Before gc")
	runtime.GC()
	t.Log("After gc")
	<-time.After(100 * time.Millisecond)
	t.Log("After sleep")
	<-time.After(1000 * time.Millisecond)
	t.Fail()
}
```
... though I completely realize this kind of thing is difficult to test conclusively.

Am I missing something / is there evidence that this works?  I assume the cost is minimal, but if I'm right I'd rather not leave it in place where it might mislead readers.

**Comment by cenkalti** [comment]
@Groxx I think you are right about this issue. The finalizer's job is releasing resources for unstopped tickers when GC is run. However, it does not get called because `run()` goroutine still has a reference to the ticker as you described. Do you suggest removing `runtime.SetFinalizer(ticker, stop)` statement? Would you make a PR?

**Comment by Groxx** [comment]
done :)

**Comment by cenkalti** [comment]
Thanks 🍰
