### ISSUE TITLE
Confused about resetting backoff

### ISSUE THREAD

**Issue by PSUdaemon** [cenkalti/backoff#60]
[Here](https://github.com/cenkalti/backoff/blob/master/retry.go#L18) you say
```
It is the caller's responsibility to reset b after Retry returns.
```
but [here](https://github.com/cenkalti/backoff/blob/master/retry.go#L35) you reset it for them before attempting the retry.

Is there a different reason I'd need to reset the backoff after return? Or are the docs wrong, or is the code?

Thanks.

**Comment by cenkalti** [comment]
@PSUdaemon Comment is wrong. Can you create a PR for removing that comment line please?
