### ISSUE TITLE
PermanentError doesn't work with popular error packages, e.g. pkg/errors

### ISSUE THREAD

**Issue by bryndin** [cenkalti/backoff#62]
https://github.com/cenkalti/backoff/blob/b7325b0f3f1097c6546ea5e83c4a23267e58ad71/retry.go#L40

This won't work if the error is wrapped into say `pkg/errors` error (https://github.com/pkg/errors) or any other custom error.   Wrapping these into `PermanentError` is even worse as no original error can be recovered.

This is pretty dangerous, as `PermanentError` will be retried in that case. 
Also it's hard to detect until you dig into the lib source and see that line above.

More details:
Typically you wrap you errors at the entry point to your code

```
func Post(...) error {
        res, err := client.Do(req)  // this is the error's entry point to your code
	if err != nil {
		return errors.Wrap(err, "bad call")  // wrap it with stacktrace etc.
	}
        if err := foo(...);  err != nil {
                 return backoff.Permanent(err)  // this one needs to be wrapped, but then it won't be PermanentError anymore
        }
}

func RetriablePost(...) error {
	operation := func() error {
		return Post(...)
	}
	err := backoff.Retry(operation, backoff.NewExponentialBackOff())
	return err
}
```

Instead it's better to return an explicit indicator of terminal error
```
	operation := func() (bool, error) {
	}
```

**Comment by rogerhub** [comment]
> Wrapping these into PermanentError is even worse as no original error can be recovered.

I don't quite follow. Why can't you get them back via `err.Error.(*YourErrorType)`?

I'm not a fan of the `PermanentError` model either (shouldn't this have been implemented with an interface assertion?), but it does get the job done without breaking existing callers. Your proposed solution would change the definition of `Operation`.

**Comment by bryndin** [comment]
>> Wrapping these into PermanentError is even worse as no original error can be recovered.

> I don't quite follow. Why can't you get them back via err.Error.(*YourErrorType)?

Because other libs, i.e. logging, expect say `pkg/errors` error and have no idea they will have to do `err.Error.Cause()` now instead of `err.Cause()`, to properly extract the original error.
See a quick sketch:  https://play.golang.org/p/FP1JAWEql8k

**Comment by bryndin** [comment]
The whole thing or wrapping errors and embedding into new structs creates a nightmare. I have to juggle with 4 types of these wrappers in my project, due to various requirements from frameworks and libs.  That's why staying away from wrapping errors if possible helps. 
For `backoff` lib it can be avoided by explicitly returning the flag `(bool, error)`. Yes, it's not backward compatible, but it doesn't create yet another wrapper the other libs have no idea about.

As of interface assertions, if I remember the specifics correctly, it has the same issue of not being useable if errors are embedded in other structures, e.g.
`type PermanentError struct {
	Err error
}
`

**Comment by rogerhub** [comment]
I think that PermanentError is intended to be used only with this module and isn't meant to be passed to other functions. Couldn't you wrap up your error in PermanentError when returning from the operation, and then unwrap it once it comes out of backoff.Retry?

`(bool, error)` would address this problem, but I think breaking backward compatibility makes this suggestion a non-starter.
