### ISSUE TITLE
Performance issue with exponential backoff

### ISSUE THREAD

**Issue by aastein** [cenkalti/backoff#63]
The constructor for an exponential backoff does calls to `rand.New`, `rand.NewSource`, and `time.Now`.

If a user of this library tries to use many concurrent backoffs these calls significantly affect the performance of the program.

Because the random field is not exported a user of this library cannot create their own instance of rand and use that to reduce the number of calls to the mentioned methods.

https://github.com/cenkalti/backoff/blob/master/exponential.go#L92
```go
func NewExponentialBackOff() *ExponentialBackOff {
	b := &ExponentialBackOff{
		InitialInterval:     DefaultInitialInterval,
		RandomizationFactor: DefaultRandomizationFactor,
		Multiplier:          DefaultMultiplier,
		MaxInterval:         DefaultMaxInterval,
		MaxElapsedTime:      DefaultMaxElapsedTime,
		Clock:               SystemClock,
		random:              rand.New(rand.NewSource(time.Now().UnixNano())),
	}
	b.Reset()
	return b
}
```

**Comment by cenkalti** [comment]
@aastein I guess this is solved by merging #58.
