### ISSUE TITLE
Retry with an already expired context.Context still tries at least once

### ISSUE THREAD

**Issue by JeremyLoy** [cenkalti/backoff#68]
Although this is very clearly documented in the documentation for `Retry`, I feel that the `operation` should not be called if the provided `context.Context` is already canceled. This has the potential to needlessly call a resource intensive function.

This is a backwards incompatible change, so the library should be bumped to `v3` if you feel that this is worth the change

**Comment by AdamSLevy** [comment]
Is this still the case?

**Comment by JeremyLoy** [comment]
I cannot confirm - I’m no longer on a project that uses this library

**Comment by cenkalti** [comment]
Yes, that is still the case. It's not possible to check if the context is canceled with current design.
I am closing this issue.
As a workaround you can check the context yourself and call `Retry` if needed.
