### ISSUE TITLE
Reset changes behaviour of exponential backoff

### ISSUE THREAD

**Issue by mhr3** [cenkalti/backoff#69]
Running this test function produces very different results depending on whether the `Reset()` call is there or not. Without the reset, the test run takes about 40seconds, and with it it's ~4.5seconds. Surely that is a bug?

```
func TestBackoff(t *testing.T) {
	ebo := backoff.NewExponentialBackOff()
	ebo.MaxElapsedTime = 30 * time.Second
	ebo.MaxInterval = 20 * time.Second
	ebo.InitialInterval = 50 * time.Millisecond

	//ebo.Reset()
	start := time.Now()
	for i := 0; i < 10; i++ {
		next := ebo.NextBackOff()
		time.Sleep(next)
	}
	fmt.Println(time.Since(start))
}
```

And because `backoff.Retry()` calls .Reset automatically, the result of using backoff manually (using .NextBackOff) vs calling .Retry is very different.

**Comment by cenkalti** [comment]
`Reset()` must have been called after re-setting fields of `ExponentialBackoff`.

**Comment by mhr3** [comment]
As you can see in the example the backoff isn't being re-used. Or are you saying that it must be initialized with a call to `Reset()`? If the latter is the case I think the docs for the reset method should be updated, cause they do not mention that requirement.

**Comment by cenkalti** [comment]
The docs should be updated.
