### ISSUE TITLE
Resource Leak: Should Stop ticker to release resource

### ISSUE THREAD

**Issue by yetingsky** [cenkalti/backoff#70]
code: https://github.com/cenkalti/backoff/blob/master/retry.go#L52

go doc: https://golang.org/pkg/time/#NewTicker

Maybe we could just use `time.After`.

**Comment by cenkalti** [comment]
Nothing leaks here. And, it's a `Timer`, not `Ticker`.

There is only one case when function returns before the timer expires and `Timer.Stop()` is called there:  https://github.com/cenkalti/backoff/blob/62661b46c4093e2c1f38d943e663db1a29873e80/retry.go#L56
