### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by AlexsJones** [cenkalti/backoff#71]
## What is the issue?

The example of:
```
// An operation that may fail.
operation := func() error {
    return nil // or an error
}

err := Retry(operation, NewExponentialBackOff())
if err != nil {
    // Handle error.
    return
}

// Operation is successful.
```
Found at: https://godoc.org/github.com/cenkalti/backoff#example-Retry

Does not work even when you correctly prefix by package e.g: 
```
// An operation that may fail.
operation := func() error {
    return nil // or an error
}

err := backoff.Retry(operation, backoff.NewExponentialBackOff())
if err != nil {
    // Handle error.
    return
}

// Operation is successful.
```

## Why?

NewExponentialBackOff does not implement `NextBackOff`

**Comment by cenkalti** [comment]
It is working. Probably, there is something wrong with your setup.

https://cl.ly/e0cc6067eed6
