### ISSUE TITLE
RetryNotify doesn't call Notify upon final failure

### ISSUE THREAD

**Issue by konradjniemiec** [cenkalti/backoff#73]
Although documented in the godocs, this behavior pushes more error handling into caller's code.

Most folks using `RetryNotify()` will have code that looks like the following:

```
if err := backoff.RetryNotify(op, backoff, handleError); err != nil {
    handleError(err)
}
```

Anyone wanting a function to be called when an error occurs, would also want it called when it is the final error.

After looking at the source code, this would require switching if statements in `retry.go`, and would not affect any tests. This would however be a breaking change, but would result in a more idiomatic behavior of the function.

**Comment by cenkalti** [comment]
Yes, that would be a breaking change.
