### ISSUE TITLE
Allow providing custom timer

### ISSUE THREAD

**Issue by aybabtme** [cenkalti/backoff#74]
The retry logic currently relies on the `time` package to create a [concrete `*time.Ticker`](https://github.com/cenkalti/backoff/blob/master/retry.go#L54) to retry, and there's no way to replace that ticker with a mocked one.  There's a way to replace the `SystemClock` with another clock, but that's not sufficient to completely avoid interaction with system time.

When testing code that uses backoff mechanisms, it's important to be able to specify precise timing scenarios, while running at full CPU speed, to obtain reliable determinisitic, non-flaky results. 

I propose:
- replacing direct usage of the `time.Ticker` type with an indirect usage, via an additional interface
-  implementing a method to provide a custom implementation of that interface

I'm opening this issue to see what you think about it. I'll follow up with a PR if you are interested.

**Comment by cenkalti** [comment]
Hello @aybabtme. If it's going to be backwards compatible, I'd like to see a PR.
