### ISSUE TITLE
incompatible with go1.13

### ISSUE THREAD

**Issue by rayjlinden** [cenkalti/backoff#78]
I get this error:
go list -m: github.com/cenkalti/backoff@v2.2.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required

I think for versions > 1.0 you need to have the code in a sub-dir.  In any case, go 1.13 does not like how you are doing versioning and giving errors.

**Comment by cenkalti** [comment]
TLDR the correct import path is `github.com/cenkalti/backoff/v3`.

There are 2 alternate mechanisms for releasing v2 or higher module. Branch or sub-directory. I chose to go with branch. v3 code lives in v3 branch. See https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher for more info.

I will be adding the new import path to README.
