### ISSUE TITLE
Provide errors.Is/As support in Permanent error

### ISSUE THREAD

**Issue by sidh** [cenkalti/backoff#79]
This is similar to https://github.com/cenkalti/backoff/issues/62, but the difference is we now have a standard way to wrap errors that is backward-compatible.

Furthermore I think there is at least one case where wrapping might be useful. You might want to decouple calling backoff.Retry and the func itself so that the func might be called without backoff.Retry at all. Wrappable Permanent error can simplify this case considerably.

**Comment by cenkalti** [comment]
@sidh I don't understand. Can you show some example code please?

**Comment by sidh** [comment]
> @sidh I don't understand. Can you show some example code please?

https://godoc.org/errors and https://blog.golang.org/go1.13-errors

_Permanent_ type should implement _Unwrap_ function so you can perform errors.Is/As checks on it without the need to explicitly typecast to it. This can be useful when you have 2 code paths, one with retry logic and one without, and want to use the same operation function code that marks errors as Permanent.
