### ISSUE TITLE
Unexpected `WithMaxRetries(backoff, 0)` behavior?

### ISSUE THREAD

**Issue by slnt** [cenkalti/backoff#80]
Something I noticed while writing a unit test is that a backoff I created as `backoff.WithMaxRetries(&backoff.ZeroBackOff{}, 0)` did not stop retrying after the first attempt failed, and kept attempting to retry. 

This is a bit different than what I expected, since I figured a max retry amount of zero would cause there to be no retries at all.

Is this expected?

**Comment by cenkalti** [comment]
If you are using `Retry` function or `Ticker` they are going to call your function or tick at least once as documented: https://godoc.org/gopkg.in/cenkalti/backoff.v3#Retry

If that is not the case, can you provide a unit test that fails?

**Comment by J-Rocke** [comment]
I actually did run into the same problem/misunderstanding a while ago. 
Since i specified maxRetries as 0 i expected exactly 1 call an NO retries. Instead it retries forever.
The unexpected thing is it is called way more often then expected.

**Comment by slnt** [comment]
@cenkalti 

I expect this test to pass:

```go
func TestShouldPass(t *testing.T) {
	var called int

	b := backoff.WithMaxRetries(&backoff.ZeroBackOff{}, 0)

	err := backoff.Retry(func() error {
		called++
		return errors.New("err")
	}, b)

	assert.Error(t, err)
	assert.Equal(t, 1, called)
}
```

Instead the function is retried forever.

**Comment by cenkalti** [comment]
Fixed in v4.
