### ISSUE TITLE
Functional options

### ISSUE THREAD

**Issue by matbur** [cenkalti/backoff#93]
First of all I want to thank you for this package. We use it a lot.

Based on this [article](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) about functional options I think it would be nice to create a BackOff like this when e.g. only one parameter differs from default.
```go
backoff.Retry(func() error {
	// do some job
	return nil
}, backoff.NewExponentialBackOff(backoff.WithMultiplier(3)))
```
The `NewExponentialBackOff` signature instead of
```go
func NewExponentialBackOff() *ExponentialBackOff 
```
would be
```go
type Option func(b *ExponentialBackOff)
func NewExponentialBackOff(...opts Option) *ExponentialBackOff 
```

These functional options could be:
```go
func WithMultiplier(x float64) Option 
func WithInitialInterval(d time.Duration) Option
```

This change would be backward compatible. Also I can create a PR.

**Comment by cenkalti** [comment]
Hello @matbur ,

Same result can be achieved with:
```go
bo := backoff.NewExponentialBackOff()
bo.Multiplier = 1234
bo.Reset()
```

I don't thing that everyone is familiar with functional options pattern and don't want to add that additional complexity to the library.

**Comment by matbur** [comment]
It can be achieved indeed, but then you are forced to save this `bo` in a variable or create some function that generates BackOff. With functional options as this package's user, you can create BackOff in place where you use it.

Change which I propose doesn't force anyone to use it if one is not familiar with functional options.

Nevertheless thanks for your time :)

**Comment by cenkalti** [comment]
Thank you :)
